### ISSUE TITLE
not a issue but why using 74hc14 ?

### ISSUE THREAD

**Issue by agsb** [frenchie68/Z79Forth#6]

**Comment by frenchie68** [comment]
Hi Alvaro,

Actually, I do use an 74HC14. The schematics has just not been updated to reflect that.
This brings power consumption down by a few milli-amps.

Are you building the board? I am experimenting with interrupt support (FIRQ in native mode).
Ideally I will have interrupt based serial communications by the end of the weekend.

All the best.

        Francois

**Comment by agsb** [comment]
Not for now, but i got curious about forth implementation and why use 74hct14 in main hardware design.
thanks.

**Comment by frenchie68** [comment]
The use of a 74HC14 as a substitute for a 74HCT14 is a perfectly working option. I am operating under these conditions myself.
